import {SUPABASE_URL,SUPABASE_ANON_KEY,AI_FUNCTION_URL,PAYMENT_FUNCTION_URL,MIDTRANS_CLIENT_KEY,MIDTRANS_SNAP_URL,WHATSAPP_NUMBER,isConfigured} from './config.js';
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=isConfigured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const fallbackProducts=[{id:'fallback-branding',name:'Branding Kit',category:'Branding',price:150000,description:'Logo, identitas visual, dan aset brand.'},{id:'fallback-design',name:'Desain Kreatif',category:'Desain',price:100000,description:'Konten, promosi, social media, dan visual campaign.'},{id:'fallback-digital',name:'Produk Digital',category:'Digital',price:75000,description:'Template dan aset digital yang siap digunakan.'},{id:'fallback-consult',name:'Konsultasi Kreatif',category:'Branding',price:100000,description:'Sesi diskusi strategi kreatif dan digital.'}];
const works=[['Brand Identity','Branding','Identitas brand yang konsisten'],['Campaign Visual','Desain','Visual promosi yang siap dipakai'],['Digital Product','Digital','Produk digital yang siap dijual'],['Social Media Kit','Desain','Paket visual media sosial'],['Creator Branding','Branding','Personal branding untuk creator'],['Landing Page','Digital','Landing page fokus konversi']];
const testimonials=[['Hasilnya rapi dan terasa lebih profesional.','Klien Kreatif'],['Komunikasi jelas, proses cepat.','Partner Digital'],['Brand kami jadi lebih konsisten.','Pemilik Brand']];
const $=id=>document.getElementById(id),rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
let products=[];let selectedProduct=null;
function gallery(){const q=($('search').value||'').toLowerCase(),f=$('filter').value;$('gallery').innerHTML=works.filter(x=>(f==='all'||x[1]===f)&&x.join(' ').toLowerCase().includes(q)).map(x=>`<article class="card"><div class="thumb">${x[0]}</div><div class="body"><span class="tag">${x[1]}</span><h3>${x[0]}</h3><p>${x[2]}</p><button class="btn mini workBtn" data-work="${x[0]}">Saya tertarik</button></div></article>`).join('');document.querySelectorAll('.workBtn').forEach(b=>b.onclick=()=>{location.hash='kontak';$('serviceSelect').value='Konsultasi Kreatif';$('orderForm').message.value='Saya tertarik dengan portfolio: '+b.dataset.work});}
function renderProducts(){ $('products').innerHTML=products.map(x=>`<article class="card"><div class="thumb">${x.name}</div><div class="body"><span class="tag">${x.category}</span><h3>${x.name}</h3><p>${x.description}</p><div class="price">${rupiah(x.price)}</div><div class="card-actions"><button class="btn mini buy" data-id="${x.id}">Beli Sekarang</button><button class="btn mini outline consult" data-service="${x.name}">Konsultasi</button></div></div></article>`).join('');document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>openCheckout(products.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.consult').forEach(b=>b.onclick=()=>{location.hash='kontak';$('serviceSelect').value=b.dataset.service;$('orderForm').message.value='Saya ingin konsultasi tentang '+b.dataset.service});}
async function loadProducts(){products=fallbackProducts;if(supabase){const {data,error}=await supabase.from('products').select('id,name,category,price,description').eq('active',true).order('created_at',{ascending:false});if(!error&&data?.length)products=data;}renderProducts();}
$('search').oninput=gallery;$('filter').onchange=gallery;gallery();loadProducts();$('testimonials').innerHTML=testimonials.map(x=>`<article class="card"><div class="body"><b>★★★★★</b><p>${x[0]}</p><small>${x[1]}</small></div></article>`).join('');
$('menu').onclick=()=>document.querySelector('#navLinks').classList.toggle('open');document.querySelectorAll('#navLinks a').forEach(a=>a.onclick=()=>document.querySelector('#navLinks').classList.remove('open'));
function wa(text='Halo ELANGKREATOR, saya ingin berkonsultasi.') {return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`}$('waLink').href=wa();$('floatingWa').href=wa();
document.querySelectorAll('.solution').forEach(b=>b.onclick=()=>{location.hash='kontak';$('serviceSelect').value=b.dataset.service;$('orderForm').message.value='Saya membutuhkan '+b.dataset.service+'. Mohon bantu jelaskan paket yang sesuai.'});
$('orderForm').onsubmit=async e=>{e.preventDefault();const s=$('formStatus');const data=Object.fromEntries(new FormData(e.currentTarget));s.textContent='Mengirim...';s.className='status';if(!supabase){s.textContent='Mode demo. Hubungkan Supabase untuk menyimpan order.';s.className='status error';return}try{const {error}=await supabase.from('leads').insert({name:data.name,email:data.email||null,phone:data.contact,service:data.service,message:data.message,source:'website'});if(error)throw error;s.textContent='Berhasil. Tim ELANGKREATOR akan menindaklanjuti.';s.className='status success';e.currentTarget.reset()}catch(err){s.textContent='Gagal menyimpan. Periksa konfigurasi Supabase.';s.className='status error'}};
function openCheckout(product){if(!product)return;selectedProduct=product;$('checkoutTitle').textContent='Checkout — '+product.name;$('checkoutSummary').innerHTML=`<b>${product.name}</b><br>${product.description}<br><strong>${rupiah(product.price)}</strong>`;$('checkoutStatus').textContent='';$('checkoutModal').classList.add('show')}
$('closeModal').onclick=()=>$('checkoutModal').classList.remove('show');$('checkoutModal').onclick=e=>{if(e.target.id==='checkoutModal')$('checkoutModal').classList.remove('show')};
async function loadMidtrans(){if(window.snap)return true;if(!MIDTRANS_CLIENT_KEY||MIDTRANS_CLIENT_KEY.includes('YOUR_'))return false;return new Promise(resolve=>{const s=document.createElement('script');s.src=MIDTRANS_SNAP_URL;s.setAttribute('data-client-key',MIDTRANS_CLIENT_KEY);s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
$('checkoutForm').onsubmit=async e=>{e.preventDefault();const s=$('checkoutStatus');const d=Object.fromEntries(new FormData(e.currentTarget));s.textContent='Menyiapkan pembayaran...';s.className='status';if(!supabase||!isConfigured){s.textContent='Supabase belum dikonfigurasi.';s.className='status error';return}try{const r=await fetch(PAYMENT_FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY,Authorization:'Bearer '+SUPABASE_ANON_KEY},body:JSON.stringify({product_id:selectedProduct.id,name:d.name,email:d.email,phone:d.phone,coupon:d.coupon||null})});const j=await r.json();if(!r.ok)throw Error(j.error||'Gagal membuat pembayaran');const ok=await loadMidtrans();if(!ok)throw Error('Midtrans Client Key belum diisi di config.js');$('checkoutModal').classList.remove('show');window.snap.pay(j.token,{onSuccess:()=>location.href='success.html?order_id='+encodeURIComponent(j.order_id),onPending:()=>location.href='success.html?order_id='+encodeURIComponent(j.order_id),onError:()=>alert('Pembayaran gagal. Silakan coba lagi.'),onClose:()=>{}})}catch(err){s.textContent=err.message;s.className='status error'}};
const messages=$('messages');function add(t,w){const d=document.createElement('div');d.className='msg '+w;d.textContent=t;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}async function ask(text){add(text,'user');if(!isConfigured){add('Mode demo: saya dapat membantu Branding Kit, Desain Kreatif, Produk Digital, dan Konsultasi Kreatif.','bot');return}const t=document.createElement('div');t.className='msg bot';t.textContent='Mengetik...';messages.appendChild(t);try{const r=await fetch(AI_FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY,Authorization:'Bearer '+SUPABASE_ANON_KEY},body:JSON.stringify({message:text})});const j=await r.json();t.remove();add(j.reply||'Maaf, saya belum bisa menjawab.','bot')}catch{t.remove();add('ELANG AI sedang tidak tersedia. Anda bisa lanjut melalui WhatsApp.','bot')}}
$('chatForm').onsubmit=e=>{e.preventDefault();const v=$('chatInput').value.trim();if(v){$('chatInput').value='';ask(v)}};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>ask(b.dataset.q));function openAI(){$('chatBody').classList.add('show');$('chatInput').focus()}$('chatToggle').onclick=()=>$('chatBody').classList.toggle('show');$('openAi').onclick=openAI;$('openAi2').onclick=openAI;
