-- ELANGKREATOR V7 database
create extension if not exists pgcrypto;
create table if not exists public.products(id uuid primary key default gen_random_uuid(),name text not null,category text not null,price numeric(12,2) not null default 0,description text not null,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.leads(id uuid primary key default gen_random_uuid(),name text not null,email text,phone text not null,service text,message text,source text default 'website',created_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_code text unique not null,name text not null,email text,phone text not null,service text not null,message text,product_id uuid references public.products(id),amount numeric(12,2) not null default 0,coupon_code text,payment_status text not null default 'pending',payment_provider text,midtrans_token text,midtrans_transaction_id text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.coupons(id uuid primary key default gen_random_uuid(),code text unique not null,discount_type text not null check(discount_type in ('percent','fixed')),discount_value numeric(12,2) not null,active boolean not null default true,expires_at timestamptz,usage_limit integer,used_count integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.testimonials(id uuid primary key default gen_random_uuid(),name text not null,role text,content text not null,rating integer not null default 5 check(rating between 1 and 5),active boolean not null default false,created_at timestamptz not null default now());
create index if not exists orders_created_idx on public.orders(created_at desc);create index if not exists leads_created_idx on public.leads(created_at desc);create index if not exists products_active_idx on public.products(active);
insert into public.products(name,category,price,description) select * from (values ('Branding Kit','Branding',150000::numeric,'Logo, identitas visual, dan aset brand.'),('Desain Kreatif','Desain',100000::numeric,'Konten, promosi, social media, dan visual campaign.'),('Produk Digital','Digital',75000::numeric,'Template dan aset digital yang siap digunakan.'),('Konsultasi Kreatif','Branding',100000::numeric,'Sesi diskusi strategi kreatif dan digital.')) v(name,category,price,description) where not exists(select 1 from public.products);
alter table public.products enable row level security;alter table public.leads enable row level security;alter table public.orders enable row level security;alter table public.coupons enable row level security;alter table public.testimonials enable row level security;
-- Public can read active catalog and submit leads. Orders are created by the Edge Function using service role.
drop policy if exists public_read_products on public.products;create policy public_read_products on public.products for select to anon,authenticated using(active=true);
drop policy if exists public_insert_leads on public.leads;create policy public_insert_leads on public.leads for insert to anon,authenticated with check(true);
drop policy if exists auth_read_orders on public.orders;create policy auth_read_orders on public.orders for select to authenticated using(true);
drop policy if exists auth_manage_products on public.products;create policy auth_manage_products on public.products for all to authenticated using(true) with check(true);
drop policy if exists auth_manage_testimonials on public.testimonials;create policy auth_manage_testimonials on public.testimonials for all to authenticated using(true) with check(true);
-- Coupons are intentionally not public-readable; validation happens server-side.
-- For production, restrict authenticated policies to your admin role/claim.
